---
# make sure python-software-properties is there
- name: Python software properties
  apt:
     name: python-software-properties
     update_cache: yes
     state: present

- apt_repository:
     repo: 'ppa:webupd8team/java'

# needs to agree the oracle java licence
- name: default true for licence agreement 1
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: default true for licence agreement 2
  shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections

# add-repository and install java8
- name: Update cache and install java8
  apt:
     name: oracle-java8-installer
     update_cache: yes
     state: present
